task_manager(venv)/task_manager/task_manager/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static 
from . import views  # Lowercase 'views'

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.index, name='index'),
    path('signup/',views.signup,name='signup'),
    path('login/',views.signin,name='signin'),
    path('accounts/', include('django.contrib.auth.urls')),
    path('task-detail/<int:task_id>/',views.task_detail,name='task_detail'),
    path("task_entry/", views.task_entry, name="task_entry")

] +static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT) # media file serving configuration 

task_manager(venv)/task_manager/task/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

class Task(models.Model):

    PRIORITY_CHOICES = [
        ('low', 'Low'),
        ('medium', 'Medium'),
        ('high', 'High'),
    ]

    user=models.ForeignKey(User,on_delete=models.CASCADE)

    title = models.CharField(max_length=100)
    description = models.TextField()
    due_date = models.DateField(null=True, blank=True)
    priority = models.CharField(max_length=10,choices=PRIORITY_CHOICES)
    task_complete = models.BooleanField(default=False)
    created = models.DateField(auto_now_add=True)
    updated = models.DateField(auto_now=True, null=True, blank=True)

    def __str__(self):
        return self.title
   

class TaskImage(models.Model):
    task = models.ForeignKey(Task,on_delete=models.CASCADE)
    image = models.ImageField(upload_to='media/taskimages')

task_manager(venv)/task_manager/task/forms.py
from django import forms
from .models import Task,TaskImage

class TaskForm(forms.ModelForm):
    class Meta:
        model = Task
        fields = ['title', 'description', 'due_date', 'priority', 'task_complete']

class TaskImageForm(forms.ModelForm):
    class Meta:
        model = TaskImage
        fields = ['image']

task_manager(venv)/task_manager/task/views.py
from django.shortcuts import render

# Create your views here.

task_manager(venv)/task_manager/task_manager/views.py
from django.shortcuts import render,redirect
from task.models import Task,TaskImage
from django.contrib.auth.models import User
from django.contrib.auth import authenticate,login,logout
from django.contrib.auth.decorators import login_required
from django.contrib import messages

from django.db.models import Q #for complex querry

from datetime import datetime
# Create your views here.
@login_required(login_url='/login/')
def index(request):
    # Retrieve tasks associated with the currently logged-in user
    tasks = Task.objects.filter(user=request.user)
    query = request.GET.get('q')  # Get the search query from the URL parameter
    filter_by = request.GET.get('filter')

    if query:
        # Filter tasks by title containing the search query
        tasks = tasks.filter(Q(title__icontains=query))

    if filter_by == 'creation_date':
        tasks = tasks.order_by('created')  
    elif filter_by == 'due_date':
        tasks = tasks.order_by('due_date')
    elif filter_by == 'priority':
        tasks = tasks.order_by('priority') 
        tasks = sorted(tasks, key=lambda x: ['high', 'medium', 'low'].index(x.priority))
    elif filter_by == 'completed':
        tasks = tasks.filter(task_complete=True)
    elif filter_by == 'active':
        tasks = tasks.filter(task_complete=False)

    context = {
        'tasks': tasks
    }

    if request.method == 'POST':
        task_id = request.POST.get('task_id')  
        if task_id:
            task = Task.objects.get(pk=task_id)
            task.task_complete = True
            task.save()




    return render(request, 'index.html', context)

def signup(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        email = request.POST.get('email')
        password = request.POST.get('password')

        # Check if username already exists
        if User.objects.filter(username=username).exists() or User.objects.filter(email=email).exists() :
            messages.error(request, 'Username or email already exists. Please try a different one.')
            return redirect('signup')  

        # Create a new User 
        user = User (
            username=username, 
            email=email,            
        )
        user.set_password(password) #set algorithm for password hashing
        user.save()
        messages.success(request, 'Account created successfully! Please login.')
        return redirect('login') 
    else:
        return render(request, 'registration/signup.html')

def signin(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')

        # Authenticate the user
        user = authenticate(request, username=username, password=password)
        
        if user is not None:
            # Log the user in
            login(request, user)
            messages.success(request, 'Logged in successfully!')
            return redirect('index')  
        else:
            messages.error(request, 'Invalid username or password.')
            return redirect('login') 

    return render(request,'registration/login.html')

@login_required(login_url='/login/')
def task_entry(request):
    if request.method == 'POST':
        # Get all the field values
        title = request.POST.get('title')
        description = request.POST.get('description')
        due_date_str = request.POST.get('due_date')
        priority = request.POST.get('priority')
        
        # Ensure the due date is parsed properly
        due_date = datetime.strptime(due_date_str, '%Y-%m-%d').date() if due_date_str else None
        
        # Retrieve the logged-in user
        user = request.user
        
        # Create the Task object associated with the user
        new_task = Task.objects.create(
            title=title,
            description=description,
            due_date=due_date,
            priority=priority,
            user=user  # Associate the task with the logged-in user
        )
        new_task.save()

        images = request.FILES.getlist('image_uploads') 
        for image in images:
            TaskImage.objects.create(task=new_task, image=image)  # Associate each image with the task      
        return redirect('index')
        
      

    return render(request, 'task_app/task_entry.html')


@login_required(login_url='/login/')
def task_detail(request,task_id):

    task=Task.objects.get(pk=task_id)
    task.due_date_formatted = task.due_date.strftime('%Y-%m-%d')
    context = {
        'task': task
    }
    
    if request.method == 'POST':
        task.title = request.POST.get('title')  # Update title
        task.description = request.POST.get('description')  # Update description    
        due_date_str = request.POST.get('due_date')
        if due_date_str:
            task.due_date = datetime.strptime(due_date_str, '%Y-%m-%d')          
        task.priority = request.POST.get('priority')  
        task.save()  # Save the updated task

        if 'delete_task' in request.POST:
            # Perform the deletion action
            task.delete()
            # Optionally, you can redirect the user after deletion
            return redirect('index')
    
        # Handle image uploads
        images = request.FILES.getlist('image_uploads')  # Get list of uploaded images
        for image in images:
            TaskImage.objects.create(task=task, image=image)  # Associate each image with the task    
        return redirect('task_detail', task_id=task.id)
                

    return render(request,'task_app/task_detail.html', context)

task_manager(venv)/task_manager/templates/base.html
<!DOCTYPE html>
<html lang="en">

<head>
  {% load static %}
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.4.1/dist/css/bootstrap.min.css"
    integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous" />
  <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js"
    integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n"
    crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"
    integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo"
    crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.4.1/dist/js/bootstrap.min.js"
    integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6"
    crossorigin="anonymous"></script>
    
    <link rel="stylesheet" href="{% static 'css/styles.css' %}" />
  <title>Task Manager</title>
</head>

<body>
  {% if user.is_authenticated %}
  <div class="pl-3 text-muted">Wellcome! {{user.email}}</div>
  {% endif %}
  
  <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <a class="navbar-brand" href="{% url 'index' %}">Task Manager App</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav"
      aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav">
        <li class="nav-item active">
          <a class="nav-link" href="{% url 'index' %}">Home</a>
        </li>
      </ul>
      <ul class="navbar-nav ml-auto"> <!-- This ul is aligned to the right -->
        {% if user.is_authenticated %}
        <li class="nav-item">
          <form action="{% url 'logout' %}" method="POST">
            {% csrf_token %}
            <button type="submit" class="btn btn-warning color-secondary tp-in-btn w-100">Logout</button>
          </form>
        </li>
        {% else %}
        <li class="nav-item">
          <a class="nav-link btn btn-secondary color-secondary tp-in-btn m-1 text-white" href="{% url 'login' %}">Login</a>
        </li>
        <li class="nav-item">
          <a class="nav-link btn btn-secondary color-secondary tp-in-btn m-1 text-white" href="{% url 'signup' %}">signup</a>
        </li>
        {% endif %}  
      </ul>
    </div>
  </nav>
  <div class="container">
    {% block content %}

    {% endblock content %}
  </div>
  


</body>

<script>
  function updateColor(selectElement) {
      var selectedPriority = selectElement.value;
      if (selectedPriority === 'low') {
          selectElement.style.backgroundColor = 'lightgreen';
      } else if (selectedPriority === 'medium') {
          selectElement.style.backgroundColor = 'lightyellow';
      } else if (selectedPriority === 'high') {
          selectElement.style.backgroundColor = 'lightcoral';
      }
  }

  // To set the color initially based on the current state
  var selectElement = document.querySelector('select[name="priority"]');
  updateColor(selectElement);
</script>

</html>

task_manager(venv)/task_manager/templates/index.html
{% extends "base.html" %}
{% load static %}
{% block content %}
<br><br>
<div class="row">
  <form class="col-10" Method='GET'>
    <div class="row">
      <div class="col-8">
        <div class="input-group">
          <input type="search" class="form-control rounded" name="q" placeholder="Search" aria-label="Search"
            aria-describedby="search-addon" />
          <button type="submit" class="btn btn-outline-primary" data-mdb-ripple-init>Search</button>
        </div>
      </div>
      <div class="col">
        <div class="dropdown">
          <button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown"
              aria-haspopup="true" aria-expanded="false">
              Filter By
          </button>
          <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
              <a class="dropdown-item" href="?filter=creation_date">Creation date</a>
              <a class="dropdown-item" href="?filter=due_date">Due date</a>
              <a class="dropdown-item" href="?filter=priority">Priority</a>
              <a class="dropdown-item" href="?filter=completed">Completed Task</a>
              <a class="dropdown-item" href="?filter=active">Active Task</a>
          </div>
      </div>
      </div>
    </div>
  </form>
<form class="col " method="POST">
    <div><a href="{% url 'task_entry' %}" class="btn btn-warning">Add Task</a></div>
</form>
</div>

<hr>
<div class="row">
  {% for task in tasks %}
<div class="col-4 py-2">
  <div class="card" style="width: 18rem;">
    <a href="{% url 'task_detail' task.id %}" style="text-decoration: none; color: black;">
      <div class="card-body">
        <div class="row justify-content-center align-items-center" style="font-size: 0.8rem;">
          <section class="col-8">Deadline: {{ task.due_date }}</section>
          <section class="col-4"
            style="{% if task.priority == 'low' %}background-color:lightgreen{% elif task.priority == 'medium' %}background-color:lightyellow{% elif task.priority == 'high' %}background-color:lightcoral{% endif %}">
            {{ task.priority }}</section>
        </div>
        <h5 class="card-title">{{ task.title }}</h5>
        <hr>
        <!-- Adjust the height of the description -->
        <p class="card-text" style="height: 100px; overflow: hidden;">{{ task.description }}</p>
      </div>
    </a>
    <div class="row">
      <div class="col">
        <form method="POST">
          {% csrf_token %}
          <input type="hidden" name="task_id" value="{{ task.id }}">
          {% if task.task_complete %}
          <input type="submit" name="submit" value="Task Completed" class="btn btn-secondary btn-block" disabled>
          {% else %}
          <input type="submit" name="submit" value="Mark As Complete" class="btn btn-warning btn-block">
          {% endif %}
        </form>
      </div>
    </div>
  </div>
</div>
{% endfor %}

</div>
{% endblock content %}

task_manager(venv)/task_manager/templates/task_app/task_detail.html
{% extends "base.html" %}
{% load static %}
{% block content %}
<br><br>
<div class="container mx-auto">
    <form method="POST" enctype="multipart/form-data" id="myForm">
        {% csrf_token %}
        <div class="card">


            <div class="card-header">
                <div class="row">
                    <div class="col-8">
                        <label for=""><h5>Task Title</h5></label>
                        <input type="text" class="form-control" id="title" name="title" value="{{ task.title }}" style="border: none; background-color: transparent;">

                    </div>
                    <div class="col">
                        <div class="row">
                            <p class="col" for="last_update">Task Create:</p>
                            <p class="col">{{task.created}}</p>
                        </div>
                        <div class="row">
                            <p class="col" for="last_update">Last Update:</p>
                            <p class="col">{{task.updated}}</p>
                        </div>
                        <div class="row">
                            <label class="col" for="due_date">Deadline:</label>
                            <input class="col" type="date" class="form-control" id="due_date" name="due_date"
                            value="{{ task.due_date_formatted }}" style="border: none;">
                        </div>
                        <div class="row">
                            <label class="col" for="due_date">Priority:</label>
                            <select class="col" name="priority" onchange="updateColor(this)" style="border: none;">
                            <option value="low" {% if task.priority == 'low' %}selected{% endif %}>Low</option>
                            <option value="medium" {% if task.priority == 'medium' %}selected{% endif %}>Medium</option>
                            <option value="high" {% if task.priority == 'high' %}selected{% endif %}>High</option>
                            </select>
                            
                        </div>
                    </div>
                </div>
            </div>
            <div class="card-body">

                <textarea class="form-control" id="description" name="description" style="border:none; min-height: 300px;" >{{ task.description }}</textarea>

            </div>

            <hr>
            <div class="row">
                <div class="col">
                    <div class="d-flex flex-row flex-wrap">
                        <!-- Cards with images displayed horizontally -->
                        {% for task_image in task.taskimage_set.all %}
                        <a href="{{ task_image.image.url }}" target="_blank">
                            <div class="card m-1" style="width: 10rem; height: 6rem; overflow: hidden;">
                                <img src="{{ task_image.image.url }}" class="card-img-top" alt="..."
                                     style="width: 100%; height: 100%; object-fit: cover;">
                            </div>
                        </a>

                        {% endfor %}
                        
                            <div class="card m-1 text-secondary" style="width: 10rem; height: 6rem; position: relative; border: 2px dashed gray;">
                                <input type="file" name="image_uploads" accept="image/*" 
                                multiple onchange="document.getElementById('myForm').submit();" 
                                multiple style="width: 100%; height: 100%; opacity: 0; cursor: pointer; position: absolute; top: 0; left: 0;">
                                <h5 style="height: 100%; display: flex; justify-content: center; align-items: center;">Add Image</h5>
                                <input type="submit" name="upload_images" value="Save Details" style="display: none;">
                            </div>
                        
                    </div>
                </div>
            </div>



            <hr>
            <div class="card-footer text-muted d-flex justify-content-between align-items-end">
                <div class="d-flex">
                    <input type="submit" class="btn btn-warning mr-2" value="Save Details">
                    <input type="submit" class="btn btn-danger" name="delete_task" value="Delete">
                </div>
                <span  class="text-right">Note: Click on the text to edit them</span>
            </div>
        </div>
    </form>

</div>
{% endblock content %}

task_manager(venv)/task_manager/templates/task_app/task_entry.html
{% extends "base.html" %}
{% load static %}
{% block content %}
<br><br>
<div class="container mx-auto">
    <form method="POST" enctype="multipart/form-data" id="myForm">
        {% csrf_token %}
        <div class="card">
            <div class="card-header">
                <div class="row">
                    <div class="col-8">
                        <label for=""><h5>Task Title</h5></label>
                        <input type="text" class="form-control" id="title" name="title" placeholder="enter task title..." style="background-color: transparent;" required>

                    </div>
                    <div class="col">
                        <div class="row">
                            <p class="col" for="last_update">Task Create:</p>
                            <p class="col">Today</p>
                        </div>
                        
                        <div class="row">
                            <label class="col" for="due_date">Deadline:</label>
                            <input class="col" type="date" class="form-control" id="due_date" name="due_date"
                            value="{{ task.due_date_formatted }}" style="border: none;" required>
                        </div>
                        <div class="row">
                            <label class="col" for="due_date">Priority:</label>
                            <select class="col" name="priority" onchange="updateColor(this)" style="border: none;">
                            <option value="low" {% if task.priority == 'low' %}selected{% endif %}>Low</option>
                            <option value="medium" {% if task.priority == 'medium' %}selected{% endif %}>Medium</option>
                            <option value="high" {% if task.priority == 'high' %}selected{% endif %}>High</option>
                            </select>
                            
                        </div>
                    </div>
                </div>
            </div>
            <div class="card-body">

                <textarea class="form-control" id="description" name="description" placeholder="task description here..." style="min-height: 300px;"></textarea>

            </div>

            <hr>
            <div class="row">
                <div class="col">
                    <div class="d-flex flex-row flex-wrap">
                            <!-- Cards with images displayed horizontally -->
                        {% for task_image in task.taskimage_set.all %}
                        <a href="{{ task_image.image.url }}" target="_blank">
                            <div class="card m-1" style="width: 10rem; height: 6rem; overflow: hidden;">
                                <img src="{{ task_image.image.url }}" class="card-img-top" alt="..."
                                     style="width: 100%; height: 100%; object-fit: cover;">
                            </div>
                        </a>

                        {% endfor %}
                        
                            <div class="card m-1 text-secondary" style="width: 10rem; height: 6rem; position: relative; border: 2px dashed gray;">
                                <input type="file" name="image_uploads" accept="image/*" 
                                multiple onchange="document.getElementById('myForm').submit();" 
                                multiple style="width: 100%; height: 100%; opacity: 0; cursor: pointer; position: absolute; top: 0; left: 0;">
                                <h5 style="height: 100%; display: flex; justify-content: center; align-items: center;">Add Image</h5>
                                <input type="submit" name="upload_images" value="Save Details" style="display: none;">
                            </div>
                        
                        
                    </div>
                </div>
            </div>



            <hr>
            <div class="card-footer text-muted d-flex justify-content-between align-items-end">
                <input type="submit" name="submit" class="btn btn-warning" value="Add Details">
            </div>
        </div>
    </form>

</div>
{% endblock content %}